---

base_locale: en
locales: [en]

data:
  external:
    - "<%= %x[bundle info decidim-admin --path].chomp %>/config/locales/%{locale}.yml"

ignore_unused:
  - decidim.admin.filters.*
  - decidim.authorization_handlers.*
  - decidim.civicrm.admin.menu.*
  - decidim.civicrm.admin.groups.show.auto_sync.*
  - decidim.civicrm.admin.meetings.*
  - decidim.civicrm.admin.meeting_registrations.sync.*
  - decidim.civicrm.admin.membership_types.index.*
  - decidim.events.civicrm_verification.*
  - decidim.system.organizations.omniauth_settings.civicrm.*
  - decidim.elections.censuses.civicrm_groups.*
  - decidim.civicrm.censuses.civicrm_groups.*
  - decidim.verifications.authorizations.civicrm_authorization.*
  - layouts.decidim.admin.civicrm.*

ignore_missing:
  - decidim.civicrm.censuses.civicrm_groups.custom_fields.*
