name: "[CI] Lint"

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

env:
  RUBY_VERSION: 3.1.1
  NODE_VERSION: 18.17.1

jobs:
  lint-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Lint and Rubocop
        run: |
          bundle exec rubocop -P
          bundle exec erblint app/**/*.erb
